# Generated by Django 5.2.16 on 2026-08-03 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('number', models.CharField(max_length=13, verbose_name='номер')),
                ('subject', models.CharField(max_length=150, verbose_name='Тема')),
                ('message', models.TextField(verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Сообщение контактной формы',
                'verbose_name_plural': 'Сообщения контактной формы',
            },
        ),
    ]
