# Generated by Django 5.2.16 on 2026-08-24 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_faq'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=110, unique=True, verbose_name='Слаг')),
                ('short_description', models.TextField(max_length=200, verbose_name='Краткое описание')),
                ('full_description', models.TextField(blank=True, null=True, verbose_name='Полное описание')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='main/products/previews/', verbose_name='Фото')),
                ('status', models.CharField(choices=[('new', 'Новинка'), ('sale', 'Распродажа'), ('sold', 'Продано')], default='new', max_length=20, verbose_name='Статус')),
                ('price', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Цена')),
                ('quantity', models.PositiveBigIntegerField(default=10, verbose_name='Кол-во в наличии')),
                ('additional', models.TextField(blank=True, null=True, verbose_name='Дополнительная информация')),
                ('sku', models.CharField(max_length=6, unique=True)),
                ('category', models.ManyToManyField(to='main.category', verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'продукты',
            },
        ),
        migrations.CreateModel(
            name='ProductComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(verbose_name='Текст')),
                ('rating', models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')], default=0, verbose_name='Рейтинг')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.product', verbose_name='Продукт')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comments', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Комментарий продукта',
                'verbose_name_plural': 'Комментарии продукта',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='main/products/photos/', verbose_name='Фото')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Фото продукта',
                'verbose_name_plural': 'Фотки продукта',
            },
        ),
    ]
